activity_labels<-read.table("activity_labels.txt")
subject_test<-read.table("test/subject_test.txt")
y_test<-read.table("test/y_test.txt")
activity_test<-sapply(y_test$V1, function(x) activity_labels[activity_labels$V1==x,"V2"])
x_test<-read.table("test/x_test.txt")
testdata<-cbind("test", subject_test, activity_test, x_test)
subject_train<-read.table("train/subject_train.txt")
y_train<-read.table("train/y_train.txt")
activity_train<-sapply(y_train$V1, function(x) activity_labels[activity_labels$V1==x,"V2"])
x_train<-read.table("train/x_train.txt")
traindata<-cbind("train", subject_train, activity_train, x_train)
features<-read.table("features.txt", colClasses=c("numeric", "character"))
heading<-gsub("-", "", features[,"V2"], fixed=TRUE)
heading<-gsub("(", "", heading, fixed=TRUE)
heading<-gsub(")", "", heading, fixed=TRUE)
heading<-gsub(",", "", heading, fixed=TRUE)
names(testdata)=c("dataset", "subject", "activity", heading)
names(traindata)=c("dataset", "subject", "activity", heading)
data<-rbind(testdata, traindata)
meanstd<-c("dataset", "subject", "activity", heading[grepl("mean()", features$V2, fixed=TRUE)], heading[grepl("std()", features$V2, fixed=TRUE)])
datameanstd<-data[,meanstd]
datasummaryBy(. ~ subject + activity, data=datameanstd, FUN=mean)